# 向量（vector）

只能包含同一类型（多个数据）的对象

## 创建向量方法

### 1、函数vector(model="logical",length=OL) 

x <- vector("character",length=10)

### 2、:      

a:b，表示从a到b

In [1]:
 x1 <- 1:4
 x1

[1] 1 2 3 4

### 3、函数c() 括号内为向量的内容

In [16]:
x2 <- c(1,2,3,4)
x2

[1] 1 2 3 4

In [11]:
x3<-c(TRUE,10,"a")#输入数据类型不一致，R会强制转换为同一种数据结构（内隐式转换）

强制转换函数 as.numeric()、as.logical()、as.character()

In [4]:
x4<-c("a","b","c")#强制转换会出现缺失值
as.numeric(x4)

Warning message in eval(expr, envir, enclos):
"强制改变过程中产生了NA"

[1] NA NA NA

查看向量属性

In [12]:
class(x1)

[1] "integer"

给向量添加名称

In [15]:
names(x1)<-c("a","b","c","d")     #names(Object)<-Name
x1

a b c d 
1 2 3 4

## 构建子集

In [1]:
x<-1:10     #R语言数组下标是从1开始的
x[1]

[1] 1

In [2]:
x[1:5]  #前5个数据

[1] 1 2 3 4 5

In [3]:
x[x>5]  #向量中大于5的数

[1]  6  7  8  9 10

In [4]:
x>5   #判断

[1] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE

In [5]:
x[x>5&x<7]     #&  and且的意思

[1] 6

In [7]:
x[x<3 | x>7]  #|  竖线是或的意思 shift+\

[1]  1  2  8  9 10

In [8]:
y<-1:4
names(y)<-c("a","b","c","d")    #y第二个元素，使用下标获取
y[2]

b 
2

In [9]:
y["b"]  #y第二个元素，使用名字获取。名字需要打双引号，注意。

b 
2

## 向量化操作

In [12]:
x<-1:5
y<-6:10
x
y
x+y   # +、-、*、/指的是向量中相应位置的元素进行简单的加减乘除。
x*y
x/y

[1] 1 2 3 4 5

[1]  6  7  8  9 10

[1]  7  9 11 13 15

[1]  6 14 24 36 50

[1] 0.1666667 0.2857143 0.3750000 0.4444444 0.5000000

In [14]:
x<-matrix(1:4,nrow=2,ncol=2)
y<-matrix(rep(2,4),nrow=2,ncol=2)  #rep:把第一个参数，重复第二个参数指定的次数
x
y
x*y
x/y
x%*%y    #%*% 矩阵的乘法。 *矩阵对应位置数字的乘法

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[,1] [,2]
[1,] 2    2   
[2,] 2    2

[,1] [,2]
[1,] 2    6   
[2,] 4    8

[,1] [,2]
[1,] 0.5  1.5 
[2,] 1.0  2.0

[,1] [,2]
[1,]  8    8  
[2,] 12   12